# auto-generated snapshot
import json
import os
import sys
import time

from iso3166 import countries

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))


from peewee import *
from datetime import datetime
import peewee

from playhouse.migrate import MySQLMigrator

from models import Player, PlayerGame, Game, Map, Zone
from settings import db

migrator = MySQLMigrator(db)


def migrate():
    try:
        zones = [
            {"alpha3": "AFG", "id": 5, "name": "Afghanistan"},
            {"alpha3": "ALA", "id": None, "name": None},
            {"alpha3": "ALB", "id": 12, "name": "Albania"},
            {"alpha3": "DZA", "id": 16, "name": "Algeria"},
            {"alpha3": "ASM", "id": 1044, "name": "American Samoa"},
            {"alpha3": "AND", "id": 21, "name": "Andorra"},
            {"alpha3": "AGO", "id": 22, "name": "Angola"},
            {"alpha3": "AIA", "id": None, "name": None},
            {"alpha3": "ATA", "id": None, "name": None},
            {"alpha3": "ATG", "id": 23, "name": "Antigua and Barbuda"},
            {"alpha3": "ARG", "id": 32, "name": "Argentina"},
            {"alpha3": "ARM", "id": 37, "name": "Armenia"},
            {"alpha3": "ABW", "id": None, "name": None},
            {"alpha3": "AUS", "id": 44, "name": "Australia"},
            {"alpha3": "AUT", "id": 46, "name": "Austria"},
            {"alpha3": "AZE", "id": 49, "name": "Azerbaijan"},
            {"alpha3": "BHS", "id": 53, "name": "Bahamas"},
            {"alpha3": "BHR", "id": 54, "name": "Bahrain"},
            {"alpha3": "BGD", "id": 55, "name": "Bangladesh"},
            {"alpha3": "BRB", "id": 57, "name": "Barbados"},
            {"alpha3": "BLR", "id": 64, "name": "Belarus"},
            {"alpha3": "BEL", "id": 65, "name": "Belgium"},
            {"alpha3": "BLZ", "id": 66, "name": "Belize"},
            {"alpha3": "BEN", "id": 67, "name": "Benin"},
            {"alpha3": "BMU", "id": None, "name": None},
            {"alpha3": "BTN", "id": 71, "name": "Bhutan"},
            {"alpha3": "BOL", "id": 74, "name": "Bolivia"},
            {"alpha3": "BES", "id": None, "name": None},
            {"alpha3": "BIH", "id": 77, "name": "Bosnia and Herzegovina"},
            {"alpha3": "BWA", "id": 78, "name": "Botswana"},
            {"alpha3": "BVT", "id": None, "name": None},
            {"alpha3": "BRA", "id": 84, "name": "Brazil"},
            {"alpha3": "IOT", "id": None, "name": None},
            {"alpha3": "BRN", "id": 88, "name": "Brunei"},
            {"alpha3": "BGR", "id": 91, "name": "Bulgaria"},
            {"alpha3": "BFA", "id": 93, "name": "Burkina Faso"},
            {"alpha3": "BDI", "id": 94, "name": "Burundi"},
            {"alpha3": "KHM", "id": 98, "name": "Cambodia"},
            {"alpha3": "CMR", "id": 99, "name": "Cameroon"},
            {"alpha3": "CAN", "id": 101, "name": "Canada"},
            {"alpha3": "CPV", "id": 104, "name": "Cabo Verde"},
            {"alpha3": "CYM", "id": None, "name": None},
            {"alpha3": "CAF", "id": 109, "name": "Central African Republic"},
            {"alpha3": "TCD", "id": 112, "name": "Chad"},
            {"alpha3": "CHL", "id": 117, "name": "Chile"},
            {"alpha3": "CHN", "id": 118, "name": "China"},
            {"alpha3": "CXR", "id": None, "name": None},
            {"alpha3": "CCK", "id": None, "name": None},
            {"alpha3": "COL", "id": 119, "name": "Colombia"},
            {"alpha3": "COM", "id": 121, "name": "Comoros"},
            {"alpha3": "COG", "id": 124, "name": "Congo"},
            {"alpha3": "COD", "id": 153, "name": "RDC"},
            {"alpha3": "COK", "id": None, "name": None},
            {"alpha3": "CRI", "id": 130, "name": "Costa Rica"},
            {"alpha3": "CIV", "id": 262, "name": "Côte d'Ivoire"},
            {"alpha3": "HRV", "id": 134, "name": "Croatia"},
            {"alpha3": "CUB", "id": 136, "name": "Cuba"},
            {"alpha3": "CUW", "id": None, "name": None},
            {"alpha3": "CYP", "id": 137, "name": "Cyprus"},
            {"alpha3": "CZE", "id": 138, "name": "Czechia"},
            {"alpha3": "DNK", "id": 141, "name": "Denmark"},
            {"alpha3": "DJI", "id": 144, "name": "Djibouti"},
            {"alpha3": "DMA", "id": 147, "name": "Dominica"},
            {"alpha3": "DOM", "id": 148, "name": "Dominican Republic"},
            {"alpha3": "ECU", "id": 161, "name": "Ecuador"},
            {"alpha3": "EGY", "id": 162, "name": "Egypt"},
            {"alpha3": "SLV", "id": 164, "name": "El Salvador"},
            {"alpha3": "GNQ", "id": 167, "name": "EquatorialGuinea"},
            {"alpha3": "ERI", "id": 169, "name": "Eritrea"},
            {"alpha3": "EST", "id": 172, "name": "Estonia"},
            {"alpha3": "ETH", "id": 173, "name": "Ethiopia"},
            {"alpha3": "FLK", "id": None, "name": None},
            {"alpha3": "FRO", "id": None, "name": None},
            {"alpha3": "FJI", "id": 180, "name": "Fiji"},
            {"alpha3": "FIN", "id": 182, "name": "Finland"},
            {"alpha3": "FRA", "id": 185, "name": "France"},
            {"alpha3": "GUF", "id": None, "name": None},
            {"alpha3": "PYF", "id": None, "name": None},
            {"alpha3": "ATF", "id": None, "name": None},
            {"alpha3": "GAB", "id": 190, "name": "Gabon"},
            {"alpha3": "GMB", "id": None, "name": None},
            {"alpha3": "GEO", "id": 195, "name": "Georgia"},
            {"alpha3": "DEU", "id": 197, "name": "Germany"},
            {"alpha3": "GHA", "id": 199, "name": "Ghana"},
            {"alpha3": "GIB", "id": None, "name": None},
            {"alpha3": "GRC", "id": 206, "name": "Greece"},
            {"alpha3": "GRL", "id": None, "name": None},
            {"alpha3": "GRD", "id": 207, "name": "Grenada"},
            {"alpha3": "GLP", "id": 209, "name": "Guadeloupe"},
            {"alpha3": "GUM", "id": 210, "name": "Guam"},
            {"alpha3": "GTM", "id": 211, "name": "Guatemala"},
            {"alpha3": "GGY", "id": None, "name": None},
            {"alpha3": "GIN", "id": 212, "name": "Guinea"},
            {"alpha3": "GNB", "id": 213, "name": "Guinea-Bissau"},
            {"alpha3": "GUY", "id": 214, "name": "Guyana"},
            {"alpha3": "HTI", "id": 218, "name": "Haiti"},
            {"alpha3": "HMD", "id": None, "name": None},
            {"alpha3": "VAT", "id": None, "name": None},
            {"alpha3": "HND", "id": 240, "name": "Honduras"},
            {"alpha3": "HKG", "id": 241, "name": "Hong Kong"},
            {"alpha3": "HUN", "id": 242, "name": "Hungary"},
            {"alpha3": "ISL", "id": 243, "name": "Iceland"},
            {"alpha3": "IND", "id": 249, "name": "India"},
            {"alpha3": "IDN", "id": 251, "name": "Indonesia"},
            {"alpha3": "IRN", "id": 255, "name": "Iran"},
            {"alpha3": "IRQ", "id": 256, "name": "Iraq"},
            {"alpha3": "IRL", "id": 257, "name": "Ireland"},
            {"alpha3": "IMN", "id": None, "name": None},
            {"alpha3": "ISR", "id": 260, "name": "Israel"},
            {"alpha3": "ITA", "id": 261, "name": "Italy"},
            {"alpha3": "JAM", "id": 263, "name": "Jamaica"},
            {"alpha3": "JPN", "id": 264, "name": "Japan"},
            {"alpha3": "JEY", "id": None, "name": None},
            {"alpha3": "JOR", "id": 268, "name": "Jordan"},
            {"alpha3": "KAZ", "id": 276, "name": "Kazakhstan"},
            {"alpha3": "KEN", "id": 278, "name": "Kenya"},
            {"alpha3": "KIR", "id": None, "name": None},
            {"alpha3": "PRK", "id": 543, "name": "North Korea"},
            {"alpha3": "KOR", "id": 543, "name": "South Korea"},
            {"alpha3": "XKX", "id": None, "name": None},
            {"alpha3": "KWT", "id": 288, "name": "Kuwait"},
            {"alpha3": "KGZ", "id": 289, "name": "Kyrgyzstan"},
            {"alpha3": "LAO", "id": 292, "name": "Laos"},
            {"alpha3": "LVA", "id": 293, "name": "Latvia"},
            {"alpha3": "LBN", "id": 295, "name": "Lebanon"},
            {"alpha3": "LSO", "id": 297, "name": "Lesotho"},
            {"alpha3": "LBR", "id": 299, "name": "Liberia"},
            {"alpha3": "LBY", "id": 300, "name": "Libya"},
            {"alpha3": "LIE", "id": 301, "name": "Liechtenstein"},
            {"alpha3": "LTU", "id": 307, "name": "Lithuania"},
            {"alpha3": "LUX", "id": 324, "name": "Luxembourg"},
            {"alpha3": "MAC", "id": None, "name": None},
            {"alpha3": "MKD", "id": 420, "name": "North Macedonia"},
            {"alpha3": "MDG", "id": 327, "name": "Madagascar"},
            {"alpha3": "MWI", "id": 334, "name": "Malawi"},
            {"alpha3": "MYS", "id": 335, "name": "Malaysia"},
            {"alpha3": "MDV", "id": 336, "name": "Maldives"},
            {"alpha3": "MLI", "id": 337, "name": "Mali"},
            {"alpha3": "MLT", "id": 338, "name": "Malta"},
            {"alpha3": "MHL", "id": 344, "name": "Marshall Islands"},
            {"alpha3": "MTQ", "id": 345, "name": "Martinique"},
            {"alpha3": "MRT", "id": 349, "name": "Mauritania"},
            {"alpha3": "MUS", "id": 350, "name": "Mauritius"},
            {"alpha3": "MYT", "id": 352, "name": "Mayotte"},
            {"alpha3": "MEX", "id": 358, "name": "Mexico"},
            {"alpha3": "FSM", "id": 360, "name": "Micronesia"},
            {"alpha3": "MDA", "id": None, "name": None},
            {"alpha3": "MCO", "id": 367, "name": "Monaco"},
            {"alpha3": "MNG", "id": 368, "name": "Mongolia"},
            {"alpha3": "MNE", "id": 370, "name": "Montenegro"},
            {"alpha3": "MSR", "id": None, "name": None},
            {"alpha3": "MAR", "id": 373, "name": "Morocco"},
            {"alpha3": "MOZ", "id": 375, "name": "Mozambique"},
            {"alpha3": "MMR", "id": 377, "name": "Myanmar"},
            {"alpha3": "NAM", "id": 378, "name": "Namibia"},
            {"alpha3": "NRU", "id": 380, "name": "Nauru"},
            {"alpha3": "NPL", "id": 383, "name": "Nepal"},
            {"alpha3": "NLD", "id": 384, "name": "Netherlands"},
            {"alpha3": "NCL", "id": None, "name": None},
            {"alpha3": "NZL", "id": 394, "name": "New Zealand"},
            {"alpha3": "NIC", "id": 396, "name": "Nicaragua"},
            {"alpha3": "NER", "id": 400, "name": "Niger"},
            {"alpha3": "NGA", "id": 401, "name": "Nigeria"},
            {"alpha3": "NIU", "id": None, "name": None},
            {"alpha3": "NFK", "id": None, "name": None},
            {"alpha3": "MNP", "id": 417, "name": "Northern Mariana Islands"},
            {"alpha3": "NOR", "id": 421, "name": "Norway"},
            {"alpha3": "OMN", "id": 439, "name": "Oman"},
            {"alpha3": "PAK", "id": 448, "name": "Pakistan"},
            {"alpha3": "PLW", "id": 449, "name": "Palau"},
            {"alpha3": "PSE", "id": None, "name": None},
            {"alpha3": "PAN", "id": 450, "name": "Panama"},
            {"alpha3": "PNG", "id": 451, "name": "Papua New Guinea"},
            {"alpha3": "PRY", "id": 452, "name": "Paraguay"},
            {"alpha3": "PER", "id": 459, "name": "Peru"},
            {"alpha3": "PHL", "id": 461, "name": "Philippines"},
            {"alpha3": "PCN", "id": None, "name": None},
            {"alpha3": "POL", "id": 466, "name": "Poland"},
            {"alpha3": "PRT", "id": 469, "name": "Portugal"},
            {"alpha3": "PRI", "id": 476, "name": "Puerto Rico"},
            {"alpha3": "QAT", "id": 481, "name": "Qatar"},
            {"alpha3": "REU", "id": 486, "name": "R\u00e9union"},
            {"alpha3": "ROU", "id": 490, "name": "Romania"},
            {"alpha3": "RUS", "id": 492, "name": "Russia"},
            {"alpha3": "RWA", "id": 493, "name": "Rwanda"},
            {"alpha3": "BLM", "id": None, "name": None},
            {"alpha3": "SHN", "id": None, "name": None},
            {"alpha3": "KNA", "id": 498, "name": "Saint Kitts and Nevis"},
            {"alpha3": "LCA", "id": 499, "name": "Saint Lucia"},
            {"alpha3": "MAF", "id": None, "name": None},
            {"alpha3": "SPM", "id": None, "name": None},
            {"alpha3": "VCT", "id": 500, "name": "Saint Vincent and the Grenadines"},
            {"alpha3": "WSM", "id": 505, "name": "Samoa"},
            {"alpha3": "SMR", "id": 506, "name": "San Marino"},
            {
                "alpha3": "STP",
                "id": 508,
                "name": "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
            },
            {"alpha3": "SAU", "id": 513, "name": "Saudi Arabia"},
            {"alpha3": "SEN", "id": 523, "name": "Senegal"},
            {"alpha3": "SRB", "id": 524, "name": "Serbia"},
            {"alpha3": "SYC", "id": 525, "name": "Seychelles"},
            {"alpha3": "SLE", "id": 527, "name": "Sierra Leone"},
            {"alpha3": "SGP", "id": 528, "name": "Singapore"},
            {"alpha3": "SXM", "id": None, "name": None},
            {"alpha3": "SVK", "id": 530, "name": "Slovakia"},
            {"alpha3": "SVN", "id": 531, "name": "Slovenia"},
            {"alpha3": "SLB", "id": 532, "name": "Solomon Islands"},
            {"alpha3": "SOM", "id": 534, "name": "Somalia"},
            {"alpha3": "ZAF", "id": 537, "name": "South Africa"},
            {"alpha3": "SGS", "id": None, "name": None},
            {"alpha3": "SSD", "id": 544, "name": "South Sudan"},
            {"alpha3": "ESP", "id": 546, "name": "Spain"},
            {"alpha3": "LKA", "id": 547, "name": "Sri Lanka"},
            {"alpha3": "SDN", "id": 553, "name": "Sudan"},
            {"alpha3": "SUR", "id": 554, "name": "Suriname"},
            {"alpha3": "SJM", "id": None, "name": None},
            {"alpha3": "SWZ", "id": None, "name": None},
            {"alpha3": "SWE", "id": 555, "name": "Sweden"},
            {"alpha3": "CHE", "id": 557, "name": "Switzerland"},
            {"alpha3": "SYR", "id": 558, "name": "Syria"},
            {"alpha3": "TWN", "id": 560, "name": "Taiwan"},
            {"alpha3": "TJK", "id": 561, "name": "Tajikistan"},
            {"alpha3": "TZA", "id": 562, "name": "Tanzania"},
            {"alpha3": "THA", "id": 570, "name": "Thailand"},
            {"alpha3": "TLS", "id": 575, "name": "Timor-Leste"},
            {"alpha3": "TGO", "id": 576, "name": "Togo"},
            {"alpha3": "TKL", "id": None, "name": None},
            {"alpha3": "TON", "id": 578, "name": "Tonga"},
            {"alpha3": "TTO", "id": 582, "name": "Trinidad and Tobago"},
            {"alpha3": "TUN", "id": 583, "name": "Tunisia"},
            {"alpha3": "TUR", "id": 584, "name": "T\u00fcrkiye"},
            {"alpha3": "TKM", "id": 585, "name": "Turkmenistan"},
            {"alpha3": "TCA", "id": None, "name": None},
            {"alpha3": "TUV", "id": 586, "name": "Tuvalu"},
            {"alpha3": "UGA", "id": 588, "name": "Uganda"},
            {"alpha3": "UKR", "id": 589, "name": "Ukraine"},
            {"alpha3": "ARE", "id": 591, "name": "United Arab Emirates"},
            {"alpha3": "GBR", "id": 592, "name": "UK"},
            {"alpha3": "USA", "id": 593, "name": "USA"},
            {"alpha3": "UMI", "id": None, "name": None},
            {"alpha3": "URY", "id": 596, "name": "Uruguay"},
            {"alpha3": "UZB", "id": 601, "name": "Uzbekistan"},
            {"alpha3": "VUT", "id": 607, "name": "Vanuatu"},
            {"alpha3": "VEN", "id": 614, "name": "Vénézuela"},
            {"alpha3": "VNM", "id": 620, "name": "Vietnam"},
            {"alpha3": "VGB", "id": None, "name": None},
            {"alpha3": "VIR", "id": None, "name": None},
            {"alpha3": "WLF", "id": None, "name": None},
            {"alpha3": "ESH", "id": None, "name": None},
            {"alpha3": "YEM", "id": 642, "name": "Yemen"},
            {"alpha3": "ZMB", "id": 649, "name": "Zambia"},
            {"alpha3": "ZWE", "id": 651, "name": "Zimbabwe"},
        ]
        for zone in zones:
            if zone["id"]:
                print(zone["name"])
                z = Zone.get(id=zone["id"])
                z.country_alpha3 = zone["alpha3"]
                z.save()
    except Exception as e:
        print(e)


if __name__ == "__main__":
    migrate()
